#!/usr/bin/env node
// PreToolUse(Edit|Write) guard: warn (non-blocking) on sensitive/generated files.
// Converted from hookify.warn-{env-files,generated-prisma,shadcn-ui}.local.md.
// Fail-safe: any error exits 0 silently.
const fs = require("fs");
try {
  const input = JSON.parse(fs.readFileSync(0, "utf8") || "{}");
  const fp = input?.tool_input?.file_path || "";
  const warns = [];
  if (/\.env(\.|$)/.test(fp)) {
    warns.push(
      "WARNING: editing a `.env*` file — contains secrets, never committed. Confirm the change is intentional and the key name matches CLAUDE.md → Environment. Prod equivalents are plain Azure Container App secrets (no Key Vault) — a local change alone does not reach prod (see docs/deployment.md)."
    );
  }
  if (/\/src\/lib\/generated\//.test(fp)) {
    warns.push(
      "WARNING: `src/lib/generated/prisma/` is generated by `npx prisma generate` — hand edits are overwritten on the next generate. Change `prisma/schema.prisma` instead, then run `npm run db:push && npx prisma generate`."
    );
  }
  if (/\/src\/components\/ui\//.test(fp)) {
    warns.push(
      "WARNING: `src/components/ui/` is shadcn-generated — project convention says do not edit directly. Wrap or extend elsewhere (a new component in the feature folder), or re-add via `npx shadcn add <component>`. Only proceed if the user explicitly asked to patch the shadcn file itself."
    );
  }
  if (warns.length) {
    process.stdout.write(
      JSON.stringify({
        hookSpecificOutput: {
          hookEventName: "PreToolUse",
          additionalContext: warns.join("\n\n"),
        },
      })
    );
  }
  process.exit(0);
} catch {
  process.exit(0);
}
