#!/usr/bin/env node
// PreToolUse(Edit|Write) guard: warn (non-blocking) on sensitive/generated files.
// Fail-safe: any error exits 0 silently.
const fs = require("fs");
try {
  const input = JSON.parse(fs.readFileSync(0, "utf8") || "{}");
  const fp = input?.tool_input?.file_path || "";
  const warns = [];
  if (/(\.env(\.|$)|\.dev\.vars$|\/wrangler\.toml$)/.test(fp)) {
    warns.push(
      "WARNING: editing a local secrets/config file (`.env*`, `.dev.vars`, `wrangler.toml`) — gitignored, never committed (public repo). Put placeholders in the `*.example` twin instead; never paste a real account_id/database_id into a tracked file."
    );
  }
  if (/\/src\/db\/migrations\//.test(fp)) {
    warns.push(
      "WARNING: `src/db/migrations/` is generated by `drizzle-kit generate` and forward-only — never hand-edit an applied migration (users' D1s already ran it). Change `src/db/schema.ts` and generate a new migration instead."
    );
  }
  if (warns.length) {
    process.stdout.write(
      JSON.stringify({
        hookSpecificOutput: {
          hookEventName: "PreToolUse",
          additionalContext: warns.join("\n\n"),
        },
      })
    );
  }
  process.exit(0);
} catch {
  process.exit(0);
}
